PYApp.controller 'userCenterCtl', ['$scope','$http',($scope,$http) ->


  ## base info
  $scope.showHints = true;

  $scope.info = {
    nickname:'mario'
    phone:11577669988
    email:'mario.ma@trantect.com'
    address:'黄埔大厦'
    avatar:'defaultAvatar.png'
  }

  $scope.uploadFile = (files) ->

    fd = new FormData()
    fd.append("file",files[0])


    $http.post('/user/upload/avatar',fd,{
      withCredentials: true,
      headers: {'Content-Type': undefined },
      transformRequest: angular.identity}
    ).then (data)->
      $scope.info.avatar = data.data.filename


  ## my post list
  $scope.totalList = 44
  $scope.currentPage = 2
  $scope.postList = [
    {
      title:'阿迪达斯拼邮1'
      link:'www.baidu.com'
      status:'open'
      applyPeople:[
        {
          uid:'11'
          username:'mario1'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'31'
            }
          ]
          status:'ok'
        }
        {
          uid:'12'
          username:'mario2'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'32'
            }
          ]
          status:'ok'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'ok'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'34'
            }
          ]
          status:'wait'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'35'
            }
          ]
          status:'wait'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'wait'
        }
      ]
    }

    {
      title:'阿迪达斯拼邮2'
      link:'www.baidu.com'
      status:'open'
      applyPeople:[
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'ok'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'ok'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'ok'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'wait'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'wait'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'wait'
        }
      ]
    }

    {
      title:'阿迪达斯拼邮3'
      link:'www.baidu.com'
      status:'open'
      applyPeople:[
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'ok'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'ok'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'ok'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'wait'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'wait'
        }
        {
          uid:'11'
          username:'mario'
          attr:[
            {
              key:'颜色'
              value:'红色'
            }
            {
              key:'大小'
              value:'33'
            }
          ]
          status:'wait'
        }
      ]
    }
  ]
  $scope.applyList = [
    {
      postId:'11'
      title:'apply1'
      owner:'mario'
      status:'pass' #pass,applying,reject
    }
  ]


  ## my apply list
]
